name: Deploy Example
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fresh-youtube"
          root: ./example
          entrypoint: "./main.ts"
          import-map: "./import_map.json"
